name: Deploy to Alibaba OSS
on:
  push:
    branches: [ main ]

env:
  OSS_BUCKET: timo-test
  OSS_CODE_PATH: test/app.zip  # OSS中的ZIP路径
  PYTHON_SOURCE_FILE: app.py   # 本地Python文件

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 配置阿里云新加坡区域凭证
      - name: Configure Alibaba Cloud Credentials
        uses: aliyun/configure-aliyun-credentials-action@v1
        with:
          access-key-id: ${{ secrets.PRE_OSS_AK_YYK }}
          access-key-secret: ${{ secrets.PRE_OSS_SK_YYK }}
          region-id: ap-southeast-1  # 新加坡区域

      # 打包app.py为ZIP（阿里云FC要求代码必须为ZIP）
      - name: Package Python code
        run: |
          zip app.zip ${{ env.PYTHON_SOURCE_FILE }}  # 将app.py打包为app.zip
          ls -lh

      # 上传到OSS（新加坡区域）
      - name: Upload to OSS
        run: |
          aliyun oss cp app.zip oss://${{ env.OSS_BUCKET }}/${{ env.OSS_CODE_PATH }} --force

      # 部署函数计算
      - name: Deploy to FC
        run: s deploy --use-local -y
        env:
          OSS_ENDPOINT: oss-ap-southeast-1.aliyuncs.com  # 新加坡OSS Endpoint
