name: Deploy to Alibaba OSS
on:
  push:
    branches: [ main ]

env:
  OSS_BUCKET: timo-test
  OSS_CODE_PATH: test/app.zip  # OSS中的ZIP路径
  PYTHON_SOURCE_FILE: app.py   # 本地Python文件

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: |
          npm install
          npm install -g @serverless-devs/s

      - name: Install osutil
        run: |
          wget http://gosspublic.alicdn.com/ossutil/1.7.1/ossutil64 -O ossutil64
          chmod +x ossutil64
          sudo mv ossutil64 /usr/local/bin/ossutil

      - name: Config ossutil
        run: ossutil config -e ${{ secrets.PRE_US_OSS_ENDPOINT_YYK }} -i ${{ secrets.PRE_OSS_AK_YYK }} -k ${{ secrets.PRE_OSS_SK_YYK }} -L CH

      # 打包app.py为ZIP（阿里云FC要求代码必须为ZIP）
      - name: Package Python code
        run: |
          sudo apt install zip -y
          zip app.zip ${{ env.PYTHON_SOURCE_FILE }}  # 将app.py打包为app.zip
          ls -lh

      # 上传到OSS（新加坡区域）
      - name: Upload to OSS
        run: |
           ossutil cp app.zip oss://${{ env.OSS_BUCKET }}/${{ env.OSS_CODE_PATH }} --force

      - name: Deploy to Function Compute
        run: |
          echo "{}" > env.yaml \
          s deploy -y --use-local \
            --env "OSS_ACCESS_KEY_ID=${{ secrets.PRE_OSS_AK_YYK }}" \
            --env "OSS_ACCESS_KEY_SECRET=${{ secrets.PRE_OSS_SK_YYK }}" \
            --env "OSS_ENDPOINT=${{ secrets.PRE_US_OSS_ENDPOINT_YYK }}"
