name: Deploy to Alibaba Cloud Function Compute

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: |
          npm install
          npm install -g @serverless-devs/s

      - name: Configure Alibaba Cloud Credentials
        uses: taixw2/deploy-aliyun-oss@v1
        with:
          region: ap-southeast-1.aliyuncs.com
          access-key-id: ${{ secrets.PRE_OSS_AK_YYK }}
          access-key-secret: ${{ secrets.PRE_OSS_SK_YYK }}
          bucket: oss://timo-test/test
          secure: true
          #entry: dist/**/*
          remote-dir: /


      - name: Deploy OSS
        uses: taixw2/deploy-aliyun-oss@v1
        with:
          # aliyun config
          region: ap-southeast-1.aliyuncs.com
          access-key-id: ${{ secrets.PRE_OSS_AK_YYK }}
          access-key-secret: ${{ secrets.PRE_OSS_SK_YYK }}
          bucket: oss://timo-test/test
          secure: true
          # deploy config
          entry: dist/**/* # glob pattern
          remote-dir: /
          path-rewrite: ^dist

      - name: Add Serverless Devs configuration
        run: s config add --AccessKeyID ${{secrets.PRE_OSS_AK_YYK}} --AccessKeySecret ${{secrets.PRE_OSS_SK_YYK}} -a default -f

      - name: Deploy to Function Compute
        run: s deploy -y --use-local
        env:
          OSS_ACCESS_KEY_ID: ${{ secrets.PRE_OSS_AK_YYK }}
          OSS_ACCESS_KEY_SECRET: ${{ secrets.PRE_OSS_SK_YYK }}
          OSS_ENDPOINT: ${{ secrets.PRE_US_OSS_ENDPOINT_YYK }}
          OSS_BUCKET_PATH: oss://timo-test/test
