name: Deploy to Alibaba OSS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: |
          npm install
          npm install -g @serverless-devs/s

      - name: Install osutil
        run: |
          wget http://gosspublic.alicdn.com/ossutil/1.7.1/ossutil64 -O ossutil64
          chmod +x ossutil64
          sudo mv ossutil64 /usr/local/bin/ossutil

      - name: Config ossutil
        run: ossutil config -e ${{ secrets.PRE_US_OSS_ENDPOINT_YYK }} -i ${{ secrets.PRE_OSS_AK_YYK }} -k ${{ secrets.PRE_OSS_SK_YYK }} -L CH

      - name: Add Serverless Devs configuration
        run: |
         s config add --AccessKeyID ${{ secrets.PRE_OSS_AK_YYK }} --AccessKeySecret ${{ secrets.PRE_OSS_SK_YYK }} -a aliyun_access -f
         #ossutil ls oss://timo-test/test



      - name: Ensure Service Exists
        run: |
          s cli fc3 create-service \
            --service-name fc3-example \
            --region ap-southeast-1 \
            --access aliyun_access \
            --description "Main service container"
      
      - name: Atomic Deployment
        run: |
          # 清除旧配置
          rm -rf .s
          
          # 全新部署（禁用缓存）
          s deploy --force --debug 3 \
            --access aliyun_access \
            --region ap-southeast-1 \
            --env "OSS_ACCESS_KEY_ID=$(echo '${{ secrets.PRE_OSS_AK_YYK }}' | base64)" \
            --env "OSS_ACCESS_KEY_SECRET=$(echo '${{ secrets.PRE_OSS_SK_YYK }}' | base64)" \
            --env "OSS_ENDPOINT=${{ secrets.PRE_US_OSS_ENDPOINT_YYK }}"
          
          # 延迟验证
          sleep 15
          s info --function --debug
