name: Deploy to Alibaba OSS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: |
          npm install
          npm install -g @serverless-devs/s

      - name: Install osutil
        run: |
          wget http://gosspublic.alicdn.com/ossutil/1.7.1/ossutil64 -O ossutil64
          chmod +x ossutil64
          sudo mv ossutil64 /usr/local/bin/ossutil

      - name: Config ossutil
        run: ossutil config -e ${{ secrets.PRE_US_OSS_ENDPOINT_YYK }} -i ${{ secrets.PRE_OSS_AK_YYK }} -k ${{ secrets.PRE_OSS_SK_YYK }} -L CH

      - name: Add Serverless Devs configuration
        run: |
         s config add --AccessKeyID ${{ secrets.PRE_OSS_AK_YYK }} --AccessKeySecret ${{ secrets.PRE_OSS_SK_YYK }} -a aliyun_access -f
         #ossutil ls oss://timo-test/test

      - name: Deploy preparation
        run: |
          # 创建标准配置目录
          mkdir -p .s
          echo "env: {}" > .s/env.yaml
    
          # 验证配置
          s config get aliyun_access
    
      - name: Deploy function
        run: |
          s deploy -y --use-local \
            --access aliyun_access \
            --env "OSS_ACCESS_KEY_ID=${{ secrets.PRE_OSS_AK_YYK }}" \
            --env "OSS_ACCESS_KEY_SECRET=${{ secrets.PRE_OSS_SK_YYK }}" \
            --env "OSS_ENDPOINT=${{ secrets.PRE_US_OSS_ENDPOINT_YYK }}" \
            --debug
    
          # 查询部署结果
          s info --service --debug
          s info --function --debug
