name: Deploy to Alibaba OSS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: |
          npm install
          npm install -g @serverless-devs/s

      - name: Install ossutil
        run: |
          curl -L https://gosspublic.alicdn.com/ossutil/1.7.0/ossutil64 -o /usr/local/bin/ossutil
          chmod +x /usr/local/bin/ossutil
          
      - name: Sync files to OSS
        env:
          ACCESS_KEY_ID: ${{ secrets.PRE_OSS_AK_YYK }}
          ACCESS_KEY_SECRET: ${{ secrets.PRE_OSS_SK_YYK }}
        run: |
          ossutil cp -r ./app.py oss://timo-test/test --access-key-id=$ACCESS_KEY_ID --access-key-secret=$ACCESS_KEY_SECRET --endpoint=ap-southeast-1.aliyuncs.com

     

      - name: Add Serverless Devs configuration
        run: s config add --AccessKeyID ${{secrets.PRE_OSS_AK_YYK}} --AccessKeySecret ${{secrets.PRE_OSS_SK_YYK}} -a default -f

      - name: Deploy to Function Compute
        run: s deploy -y --use-local
        env:
          OSS_ACCESS_KEY_ID: ${{ secrets.PRE_OSS_AK_YYK }}
          OSS_ACCESS_KEY_SECRET: ${{ secrets.PRE_OSS_SK_YYK }}
          OSS_ENDPOINT: ${{ secrets.PRE_US_OSS_ENDPOINT_YYK }}
          OSS_BUCKET_PATH: oss://timo-test/test
