name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job1: 
    name: "job1"
    
      # The type of runner that the job will run on
    runs-on: [self-hosted, yyk]

    # Steps represent a sequence of tasks that will be executed as part of the job
    defaults:
      run:
        working-directory: /home/ecs-user/scripts
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Run the scripts
        run: |
          /home/ecs-user/scripts/flask.sh
