
on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/**


jobs:
  Upload-to-OSS:
    if: ${{ github.event_name == 'push' || github.event.inputs.selected_jobs  == 'Increment-upload' || github.event.inputs.selected_jobs == 'Full-upload' }}
    runs-on: [self-hosted, yyk,pre]
    env:
      PROJECT: “timo-project”
      ID_FILE: "/home/ecs-user/.timo_commit_id.txt"
      OSS_ACCESS_KEY_ID: ${{ secrets.PRE_OSS_AK_YYK }}
      OSS_ACCESS_KEY_SECRET: ${{ secrets.PRE_OSS_SK_YYK}}
      OSS_ENDPOINT: ${{ secrets.PRE_US_OSS_ENDPOINT_YYK}}
      OSS_PATH: ${{secrets.PRE_US_OSS_PATH_YYK}}
      BUCKET_PATH: "oss://timo-test/"

      steps:

        # 1. 检出代码
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            fetch-depth: 20  # 拉取最近 20 次提交

        # 2. 检查上次的 commit ID
        - name: Get Last commit ID
          run: |
            BRANCH=`git branch --show-current`
            cd timo0799 && git pull
            COMMIT_ID=$(grep ^$PROJECT  $ID_FILE |awk '{print $2}')
            if [ -z "$COMMIT_ID" ]; then
              echo "Error Commit ID. Exiting..."
              echo "Please Check $ID_FILE,  Example:"
              echo "<project_name> <last_commit_id> "
              exit 1
            else
              echo "last commit_id: $COMMIT_ID"
            fi

        # 3. 上传构建文件到阿里云 OSS
        - name: Configure Alibaba Cloud OSSUTIL
          run: ossutil64 config -i ${OSS_ACCESS_KEY_ID} -k ${OSS_ACCESS_KEY_SECRET} -e ${OSS_ENDPOINT} -c .ossutilconfig
        - name: Upload to Alibaba Cloud OSS
          run: |
            pwd
            set -e

            if [ "${{ github.event.inputs.selected_jobs }}" == "Full-upload" ]; then  
              LOCAL_PATH=("./build/games/res/")
              BUCKET_PATH=("oss://timo-test/")
        ############# 增量 ##################
            else  
              COMMIT_ID=$(grep ^$PROJECT  $ID_FILE |awk '{print $2}')
              REPO=`basename $(git rev-parse --show-toplevel)`_$PROJECT
              LOCAL_PATH=("/tmp/$REPO/build/games/res/")
              BUCKET_PATH=("oss://cp-games-pre-us/")

              for m in "${LOCAL_PATH[@]}"; do
                mkdir -p "$m"
              done

              for i in `git diff --name-only $COMMIT_ID HEAD |grep ^build`
              do
                if [  -e "$i" ]; then
                  rsync -R $i /tmp/$REPO/
                else
                  continue
                fi
              done
            fi

            for i in "${!LOCAL_PATH[@]}"; do
              
              ossutil64 -c $HOME/.ossutilconfig cp -r ${LOCAL_PATH[i]} ${BUCKET_PATH[i]}  #将目录同步到 OSS

    
            if [ "${{ github.event.inputs.selected_jobs }}" != "Full-upload" ]; then
              rm -rf /tmp/$REPO
            fi

        # 4. 保存 commit ID
        - name: Save Commit ID to file
          run: |
            HEAD_ID=`git rev-parse HEAD`
            sed -i "s/^$PROJECT .*/$PROJECT $HEAD_ID/" $ID_FILE
