name: timo flask app

on:
  push:
    branches: timo
    paths-ignore:
      - .github/workflows/**
  workflow_dispatch:
    inputs:
      selected_jobs:
        description: "Choose Increment or Full"
        required: true
        default: "Increment-upload"
        type: choice
        options:
        - timo-Increment-upload
        - timo-full-upload

jobs:
  run-flask:
    if: ${{ github.event_name == 'push' || github.event.inputs.selected_jobs  == 'Increment-upload' || github.event.inputs.selected_jobs == 'Full-upload' }}
    runs-on: [self-hosted, yyk]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run python
        run: sudo /root/.venv/bin/python3 /home/ecs-user/yyk/timo0799/app.py &
